INSERT INTO TASK (ID, NAME, COMPLETED, PRIORITY, DESCRIPTION) VALUES (1, 'Dzien dobry', true, 2, 'opis');
INSERT INTO TASK (ID, NAME, COMPLETED, PRIORITY, DESCRIPTION) VALUES (2, 'Czesc', true, 1, 'ops2');
