CREATE TABLE TASK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR (250) NOT NULL,
    COMPLETED BOOLEAN NOT NULL DEFAULT 0,
    PRIORITY INT NOT NULL,
    DESCRIPTION VARCHAR (250) NOT NULL,
    USER_ID INT
);


CREATE TABLE USER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR (250) NOT NULL,
    PASSWORD VARCHAR (250) NOT NULL,
    EMAIL VARCHAR (250) NOT NULL,
    FIRST_NAME VARCHAR (250) NOT NULL,
    LAST_NAME VARCHAR (250) NOT NULL,
    CITY VARCHAR (250) NOT NULL,
    STREET VARCHAR (250) NOT NULL,
    ACTIVATION_ID VARCHAR (250),
    CODE_NUMBER VARCHAR (250),
    ACTIVATED BOOLEAN NOT NULL DEFAULT 0
);
